language: node_js
node_js:
- node
- '12'
addons: ssh_known_hosts:134.209.208.110 
sudo: required
script: 'true'
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- mv id_rsa ~/.ssh/id_rsa
- cd front-end/
install:
- npm install
after_success:
- npm run build
- cd ..
- bash ./deploy.sh
