language: node_js
node_js:
    - node
    - '12'
addons: ssh_known_hosts:157.230.229.147
sudo: required
script: 'true'
before_install:
    - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
      -in id_rsa.enc -out id_rsa -d
    - chmod 600 id_rsa
    - mv id_rsa ~/.ssh/id_rsa
install:
    - cd front-end/
    - npm install
    - npm run build
    - cd ../back-end
    - npm install
    - npm test
after_success:
    - cd ..
    - bash ./deploy.sh